In [1]:
import pandas as pd
from os import walk

"""import the order datas into a dataframe""" 

# Use path to data files.
order_path = "season_2/test_set_2/order_data/" 
_, _, filenames = next(walk(order_path), (None, None, []))

mSeq = len(filenames)
frame = pd.DataFrame()
list_ = []

# Uncomment these lines to import all the data 
for i in range(mSeq-1):
    # White Space as Delim, import all the data file.
    df = pd.read_csv(str(order_path) + filenames[i+1],  delim_whitespace = 1, dtype = str, header = None) 
    list_.append(df)
orders = pd.concat(list_)

# Only import the data of the first day
# orders = pd.read_csv(str(order_path) + filenames[1], delim_whitespace = 1, dtype = str,  header = None) 

# Rename all the columns.
orders.columns = ['order_id', 'driver_id', 'passenger_id', 
                  'start_district_hash', 'dest_district_hash', 
                  'price', 'date', 'time']
# Convert the Date and Time column in orders from an object to a datetime value. 
# This makes it easier to work with as a date.
# Extract the year and month from from date_time, and assign them to their own columns.
orders['datetime'] = pd.to_datetime(orders['date'] + ' ' + orders['time'])
orders = orders.drop('time', 1)
orders['day'] = orders["datetime"].dt.day
# Every 10 minutes is considered as a time slot. It can be calculated by following fomula
orders['time_slot'] = orders["datetime"].dt.hour*6 + orders["datetime"].dt.minute//10

In [2]:
orders

,order_id,driver_id,passenger_id,start_district_hash,dest_district_hash,price,date,datetime,day,time_slot
0,a903b5f7f65f1dc7f4ee94fec74673be,9f7c54ffa25d8d5fe6a0794d748e41fb,dce1e90fc91ed39a7b04a22d02910a7d,d4ec2125aff74eded207d2d915ef682f,d4ec2125aff74eded207d2d915ef682f,12,2016-01-23,2016-01-23 07:20:52,23,44
1,b7c838beaf12a2132776a1f00e016038,dc02417e52e459c84b6dcb6411d70ede,1f39eba5ce330f20c95177826a122e12,2407d482f0ffa22a947068f2551fe62c,2407d482f0ffa22a947068f2551fe62c,7,2016-01-23,2016-01-23 13:08:17,23,78
2,0e0d3c93298ed59281352e34c6f1ec5a,8edb59da1224587c9043db0a1314211e,8e4e2bc0342b3c55edea2723f6613e36,b26a240205c852804ff8758628c0a86a,3a43dcdff3c0b66b1acb1644ff055f9d,30,2016-01-23,2016-01-23 15:20:07,23,92
3,1f6d0d7f68f216c4333969d6152a0a8b,4c798848442ee517b98cd61dbb674e48,5a33393e516673c8e9a065915667a30f,4725c39a5e5f4c188d382da3910b3f3f,4725c39a5e5f4c188d382da3910b3f3f,6,2016-01-23,2016-01-23 17:09:38,23,102
4,bcf6050d9f5b270f8beb3ff80b01b435,542a42a009954dd2cccfb12f0856859e,f0232b8e45abc5ca92ca0f90fa811e7c,dd8d3b9665536d6e05b29c2648c0e69a,a5609739c6b5c2719a3752327c5e33a7,17,2016-01-23,2016-01-23 19:01:31,23,114
5,cbd2663a73f6b8f48ce5a9c94f2000e1,6df7fb435f3c144af6e2524de16129e0,aa5a513b5649e2e69cfd9c25129feb72,91690261186ae5bee8f83808ea1e4a01,74c1c25f4b283fa74a5514307b0d0278,53,2016-01-23,2016-01-23 17:28:00,23,104
6,1481a0360f4bbda45d1f6030b406ee9d,4af1599195b703b66905c8321c8b7eee,ba659376d2fa7e575136e3c2a82ca368,2407d482f0ffa22a947068f2551fe62c,2407d482f0ffa22a947068f2551fe62c,19,2016-01-23,2016-01-23 09:21:18,23,56
7,fcab91de6b944dd2925a2f463558b102,b2e77960fde699f351064a66e7d0e263,1064b2931e293c0d92ed1737c0f1cf30,2407d482f0ffa22a947068f2551fe62c,929ec6c160e6f52c20a4217c7978f681,34.1,2016-01-23,2016-01-23 13:06:52,23,78
8,0aea9ed7cdb02e5a2dfb18b37451cc54,ef5e60c4305389d388ebf647c87fd836,3c6e75d7ec9f88c3ffb9729c46d3c74d,d4ec2125aff74eded207d2d915ef682f,2407d482f0ffa22a947068f2551fe62c,21.3,2016-01-23,2016-01-23 17:27:12,23,104
9,1f61f832d02e24d75d344c51627a3a87,f9168daa3c627bfa4178613682091507,0e4b60bd614fe3974abb070a12254cd9,2920ece99323b4c111d6f9affc7ea034,d4ec2125aff74eded207d2d915ef682f,7,2016-01-23,2016-01-23 13:20:55,23,80
10,02d9cdc9039765ac49bc377be32bd0f7,a2f6487303b8cf7d24128d9c8a4203f4,47e866d25d17d7269a091b65b6b8649d,2407d482f0ffa22a947068f2551fe62c,62afaf3288e236b389af9cfdc5206415,22,2016-01-23,2016-01-23 07:14:26,23,43
11,fa3add12202304a726368239bfc26835,NaN,47e866d25d17d7269a091b65b6b8649d,2407d482f0ffa22a947068f2551fe62c,62afaf3288e236b389af9cfdc5206415,22,2016-01-23,2016-01-23 07:14:26,23,43
12,0d5ff49caa748abb7880ed91434357b8,fc80fbdd76a0666c64d542022038ce98,738a809f4306ddae504bb5fa73abc218,91690261186ae5bee8f83808ea1e4a01,74c1c25f4b283fa74a5514307b0d0278,12,2016-01-23,2016-01-23 21:07:58,23,126
13,048b430614ff9d7c61fcbde34632675a,1848989744a7b633c76644909617e06f,0e93f6843b209acc82753f2dc8349c7c,b26a240205c852804ff8758628c0a86a,d1ab2cc538d518758a1a82b1787592d4,9,2016-01-23,2016-01-23 17:11:44,23,103
14,bbc9f38110c3e5d8c4506b01841cc957,db9ee24c483fd78e80e761d3c634e720,224f4ba688fdf799cda1f5fecca00387,62afaf3288e236b389af9cfdc5206415,62afaf3288e236b389af9cfdc5206415,10,2016-01-23,2016-01-23 09:04:44,23,54
15,0513a92161e722925048a8292759125e,NaN,f663a841e9103148a4db16a79da37112,b26a240205c852804ff8758628c0a86a,929ec6c160e6f52c20a4217c7978f681,69,2016-01-23,2016-01-23 19:25:36,23,116
16,0c8b1e852ea2cc2b9602e4d321a4cb64,7d7f8f400f641e339de272a99a134714,d67975d03b80403afabfcc49d096c74d,d4ec2125aff74eded207d2d915ef682f,d4ec2125aff74eded207d2d915ef682f,9,2016-01-23,2016-01-23 21:29:15,23,128
17,00cff61182cef498baec85760d2ef76a,e71cd1b86e4a41287f18a22c000297cd,381383c5d59b4068cf037cff265c04f9,b702e920dcd2765e624dc1ce3a770512,b702e920dcd2765e624dc1ce3a770512,7,2016-01-23,2016-01-23 21:22:44,23,128
18,d6d9360d375260ab37bc9beac2b58458,909efb9ad27906a84c0b90f222dd6491,e9662c9c3262f2e438108e1046e0e19b,2407d482f0ffa22a947068f2551fe62c,62afaf3288e236b389af9cfdc5206415,31,2016-01-23,2016-01-23 23:20:43,23,140
19,e603cad9886af32095bbc1c031d117e9,251d8accdfe9b4afeeb8d10fa3223b72,03543882435aa78a01346e63b12ef165,62afaf3288e236b389af9cfdc5206415,62afaf3288e236b389af9cfdc5206415,7,2016-01-23,2016-01-23 09:19:32,23,55
20,f9c0ace00e1ff11f3364e590a9a9a1e2,31a5f2b13ffca8337bad69d408ee8df9,03543882435aa78a01346e63b12ef165,62afaf3288e236b389af9cfdc5206415,62afaf3288e236b389af9cfdc5206415,8.1,2016-01-23,2016-01-23 09:19:32,23,55
21,4d7828983b5304360dc67401183b1ad6,1b8a83e9a721df8555e5778225489d88,06760e9212fb2214ebc77c2cfe078cf8,d4ec2125aff74eded207d2d915ef682f,62afaf3288e236b389af9cfdc5206415,16.5,2016-01-23,2016-01-23 15:20:36,23,92
22,02fffad1e15f481af0556704323d94a8,da0c87f67c9c2b2aa2ac58ad64380e19,c3feca068d848633e7f9812da88a7f63,fc34648599753c9e74ab238e9a4a07ad,87285a66236346350541b8815c5fae94,10,2016-01-23,2016-01-23 23:20:21,23,140
23,b17188d3d1f494dbc3d5e2421872bedc,d7448159268eb7adefb23d2b87e21883,edbee565a252659efc9f6cedadf24155,825a21aa308dea206adb49c4b77c7805,74c1c25f4b283fa74a5514307b0d0278,21,2016-01-23,2016-01-23 17:09:07,23,102
24,180543673e6c7a8abc9ce6b592934889,8d30d0712b6b46ffce434bcb404f1066,64c1d17a560c8845c9d7db1ed4146d8c,2920ece99323b4c111d6f9affc7ea034,62afaf3288e236b389af9cfdc5206415,13.6,2016-01-23,2016-01-23 09:26:51,23,56
25,31bcca3b90b4d971697156b63900d514,6cf8240b3059fac5ae03f285b945b8f8,172b54135139345fb9d24d0b23635387,90c5a34f06ac86aee0fd70e2adce7d8a,90c5a34f06ac86aee0fd70e2adce7d8a,6,2016-01-23,2016-01-23 19:09:39,23,114
26,0992fc0980cb2314af9123def3f86a4d,NaN,43e40cfd176272188f92c0813a67a592,62afaf3288e236b389af9cfdc5206415,62afaf3288e236b389af9cfdc5206415,7,2016-01-23,2016-01-23 15:21:06,23,92
27,99c9cfdeed97c32e86d7ad3556689c18,7d69a29d4c6be407ab45b2a9a5b74da5,43e40cfd176272188f92c0813a67a592,62afaf3288e236b389af9cfdc5206415,62afaf3288e236b389af9cfdc5206415,7,2016-01-23,2016-01-23 15:21:06,23,92
28,f99970f819c94b7697cc12a9c1a39800,48be3259fffa364a98ba51e5e630adce,92be280560e4d638ad00b389812c59bc,2407d482f0ffa22a947068f2551fe62c,91690261186ae5bee8f83808ea1e4a01,3,2016-01-23,2016-01-23 11:17:42,23,67
29,f195634dbe98d5f5c088db34811c0fa5,96d31c1c5007729c5f446e435fb300e1,67206de6d1c5bbcc8b08e38f3819c61a,1afd7afbc81ecc1b13886a569d869e8a,2407d482f0ffa22a947068f2551fe62c,17.1,2016-01-23,2016-01-23 17:23:57,23,104
...,...,...,...,...,...,...,...,...,...,...
102255,22ace83069ebf260bc778b24e91fa659,82e86da9eb55f3b8e876092a89a14111,fbe50e17fc65ef4030e9e2422e08e051,90c5a34f06ac86aee0fd70e2adce7d8a,90c5a34f06ac86aee0fd70e2adce7d8a,9,2016-01-31,2016-01-31 15:17:12,31,91
102256,4da12b5756211c8d8a8389092d813b0a,6a757dfbe9d1a2da70a27c8575d27ac4,fbe50e17fc65ef4030e9e2422e08e051,90c5a34f06ac86aee0fd70e2adce7d8a,90c5a34f06ac86aee0fd70e2adce7d8a,8,2016-01-31,2016-01-31 15:17:12,31,91
102257,6fc1a2aedde170169a2626ccffcbe4a4,6361778131d36857dc507005bed0aeb5,807120c48e8853ba79fee9c6cf3d9329,b05379ac3f9b7d99370d443cfd5dcc28,82cc4851f9e4faa4e54309f8bb73fd7c,11,2016-01-31,2016-01-31 19:18:27,31,115
102258,7192d406d43fed0089157a831a4bf5c7,f8c2a1ac1586b8362ed66e424d7a08ac,bbb690dc9b2929fda315f237ac2c5e3b,82cc4851f9e4faa4e54309f8bb73fd7c,d4ec2125aff74eded207d2d915ef682f,26,2016-01-31,2016-01-31 13:09:54,31,78
102259,073148f009e1cefe220b73df6f1976d7,70b9c8e4ec10a8439bb010d7afdb7fb6,e51ce341a6e6fd11bc675b05b19181d7,a5609739c6b5c2719a3752327c5e33a7,d4ec2125aff74eded207d2d915ef682f,49,2016-01-31,2016-01-31 11:15:12,31,67
102260,15f35c314e348cbdc0b4e91fc7ed8c47,e82285ebe6ec0d4debdc31bcc9bf8056,e51ce341a6e6fd11bc675b05b19181d7,a5609739c6b5c2719a3752327c5e33a7,d4ec2125aff74eded207d2d915ef682f,49,2016-01-31,2016-01-31 11:15:12,31,67
102261,c17623a0794b8281411ed08908db9390,66817b5e230c3bca7fe846da8ed7f0de,4b00246cd768d1fe395409dd55cf73f1,82cc4851f9e4faa4e54309f8bb73fd7c,4725c39a5e5f4c188d382da3910b3f3f,8,2016-01-31,2016-01-31 19:29:27,31,116
102262,c4c8fcc3154fb57ed87a485bd17e1446,NaN,7c72294f9f4826735ef9374f88dcc9f7,929ec6c160e6f52c20a4217c7978f681,82cc4851f9e4faa4e54309f8bb73fd7c,10,2016-01-31,2016-01-31 17:27:20,31,104
102263,9a8e07201b40bb3dddf5cfb24967051a,0532dd7a8c6251ef36ae26ac90d6cc7d,0bf9e109f43652249ad212e49a9c68ff,74c1c25f4b283fa74a5514307b0d0278,2308e5edf2fbee52203b5c262f557ddf,10,2016-01-31,2016-01-31 21:13:11,31,127
102264,03e397755977a51efccd6c4e9064cf56,f81a79448312431ff619c9c601e63ac7,b96ee7e469cee80e23a6a2c467d8909d,d4ec2125aff74eded207d2d915ef682f,d4ec2125aff74eded207d2d915ef682f,9,2016-01-31,2016-01-31 15:06:13,31,90
102265,c6c954116388232e9d893901d811e44c,7ed87965d8e40c48fee0233e1e6229ad,467bfe09aafdf2005f43d55c1e22e039,d4ec2125aff74eded207d2d915ef682f,d4ec2125aff74eded207d2d915ef682f,8,2016-01-31,2016-01-31 17:02:31,31,102
102266,d3364dd2b5b137be6f7fa49a0cb1c312,0e53b64f7ebc7ad79c5f4abd52091169,fecb38e3f11df5928bc8d1343764fef0,3a43dcdff3c0b66b1acb1644ff055f9d,3a43dcdff3c0b66b1acb1644ff055f9d,2,2016-01-31,2016-01-31 17:03:40,31,102
102267,36ba3bc99dfed5a33d099dd0d07bc70d,a13e851fe2a28f32a88c9b76bf80ba81,fecb38e3f11df5928bc8d1343764fef0,3a43dcdff3c0b66b1acb1644ff055f9d,3a43dcdff3c0b66b1acb1644ff055f9d,8,2016-01-31,2016-01-31 17:03:40,31,102
102268,ddcc90a0fabdc2d276295a0007b69511,5697fcff00de372006eb73d37cc33b25,dd736911d2bf44e85ab549df5c88c49c,3a43dcdff3c0b66b1acb1644ff055f9d,3a43dcdff3c0b66b1acb1644ff055f9d,7,2016-01-31,2016-01-31 21:16:35,31,127
102269,85ebc7eac0f3e9f226361b391e4707f4,NaN,56018323b921dd2c5444f98fb45509de,b05379ac3f9b7d99370d443cfd5dcc28,d1ab2cc538d518758a1a82b1787592d4,8,2016-01-31,2016-01-31 19:03:46,31,114
102270,51afb49704987adee233afd176cf64f0,cdbea133e48afda40b04523941af6cd2,69c43bdad26d8cf7ca5753e53d639086,c9f855e3e13480aad0af64b418e810c3,364bf755f9b270f0f9141d1a61de43ee,17,2016-01-31,2016-01-31 13:03:36,31,78
102271,44685e75506f652b995d8fa644a847a4,c3631673b1c62288798a374b9b700461,69c43bdad26d8cf7ca5753e53d639086,c9f855e3e13480aad0af64b418e810c3,364bf755f9b270f0f9141d1a61de43ee,14,2016-01-31,2016-01-31 13:03:36,31,78
102272,5537e9343a3f2295a13b68309412d95e,599efde2346b51d467e93f69acf67876,610ae755a3c3eae02ea3ae7014c35a21,4725c39a5e5f4c188d382da3910b3f3f,929ec6c160e6f52c20a4217c7978f681,29,2016-01-31,2016-01-31 23:22:57,31,140
102273,c06f95cc57e9543d8fb3266afa2e0ce1,224e9dcbecf6ca0cd5e87b7e66ebfc4e,33fa7637d00c43d07cbb040241cc3936,90c5a34f06ac86aee0fd70e2adce7d8a,90c5a34f06ac86aee0fd70e2adce7d8a,7,2016-01-31,2016-01-31 09:19:43,31,55
102274,56b15083977f2bb56a81faa2cf2f3515,NaN,ae0986a098dfd90fab6d0c5e0636f0ad,b05379ac3f9b7d99370d443cfd5dcc28,ad45698ea16e22c9a01df8000f1f9ee3,10,2016-01-31,2016-01-31 13:11:46,31,79
102275,e605390fa8d608f8b8e30dc0f4db5a77,NaN,30dfab7ffeeaae3670f884bcb512d9ca,2920ece99323b4c111d6f9affc7ea034,d4ec2125aff74eded207d2d915ef682f,18.8,2016-01-31,2016-01-31 07:00:24,31,42
102276,e92859560c2045b9f5466f49787d6049,NaN,b1d89f6732e1f88c14af9a18296b07d8,38d5ad2d22b61109fd8e7b43cd0e8901,b05379ac3f9b7d99370d443cfd5dcc28,7,2016-01-31,2016-01-31 11:04:30,31,66
102277,dec13f0595cc0b6a493fb0dc2d266e13,NaN,0169e3d82a85d97cf4230bb71eca30ac,90c5a34f06ac86aee0fd70e2adce7d8a,90c5a34f06ac86aee0fd70e2adce7d8a,3,2016-01-31,2016-01-31 13:22:47,31,80
102278,6e8cb0569a491794494c935648515b81,0c8a4bffe4bbbbb5abd8ad8a44e9c739,b891478e02edef162a6c82d48631afde,f2c8c4bb99e6377d21de71275afd6cd2,ba32abfc048219e933bee869741da911,8,2016-01-31,2016-01-31 21:27:29,31,128
102279,e158599ee8936a6e3e717c51dc89d9cb,10ebb38068ec1c8d0ec576d28fc68825,f9652481315cc721d5b31e007967b3d6,ca064c2682ca48c6a21de012e87c0df5,905ac1f4c0f46a8d31ac4dc68cef54ca,11,2016-01-31,2016-01-31 17:10:37,31,103
102280,6570829d18856f1e3e344c05de8c7ec6,a075868fba1853758e5ad10980e63495,26276bc27543c70f9f347b66f91eb600,4725c39a5e5f4c188d382da3910b3f3f,929ec6c160e6f52c20a4217c7978f681,7,2016-01-31,2016-01-31 21:02:14,31,126
102281,6ac106368d2a54fe24e92fba8c891fce,a10df6ba2d7f79b07d8367a2c6b99150,b23d2b6b14f8f95e1603dcece3649dc9,91690261186ae5bee8f83808ea1e4a01,d4ec2125aff74eded207d2d915ef682f,29.7,2016-01-31,2016-01-31 09:11:23,31,55
102282,64957110d6cff7f94dcc23dd359b273c,1b1d454043d3f8d3a115da5e1347cf97,742e8f68abd9a29ef04f3dd597166b9b,62afaf3288e236b389af9cfdc5206415,905ac1f4c0f46a8d31ac4dc68cef54ca,10,2016-01-31,2016-01-31 07:00:44,31,42
102283,548514c7055fed9ae70d654689b86535,30d1e6ffd19498cf1c4272f601bdf6b2,56018323b921dd2c5444f98fb45509de,364bf755f9b270f0f9141d1a61de43ee,364bf755f9b270f0f9141d1a61de43ee,6,2016-01-31,2016-01-31 17:25:14,31,104
102284,1f9174c3542bf2b0fe12452000964680,836de9a94476e9ffe1cd16fda3651950,6c96ec6e8a42ce61eee9201eaadba36e,91690261186ae5bee8f83808ea1e4a01,a814069db8d32f0fa6e188f41059c6e1,19.5,2016-01-31,2016-01-31 13:00:19,31,78

In [3]:
"""Categorize the start and destination with its id in """

# Import the hash id into a dictionary
cluster_path = "season_1/training_data/cluster_map/"
cluster = {}
with open(cluster_path + "cluster_map") as f:
    for line in f:
       (key, val) = line.split()
       cluster[str(key)] = val
        
# Update the start and destination district ID
orders['start_district_id'] = orders['start_district_hash'].map(cluster)
orders['dest_district_id'] = orders['dest_district_hash'].map(cluster)

In [4]:
# Now try to generate the gap data. We're looking for the orders which were not answered by a driver.
# Hence we extract the orders with missing driver and count the number of them in each distrct and time slot.
# The number of the not answered orders should be the gap we're looking for

gaporders = orders[pd.isnull(orders['driver_id'])]
gap = pd.DataFrame({'gap' : gaporders.groupby( ['date', 'start_district_id', 'time_slot'] ).size()}).reset_index()
gap['key'] = gap.date.astype(str).str.cat(gap.start_district_id.astype(str), sep='_').str.cat(gap.time_slot.astype(str), sep='_')
gap["district_id"] = gap['start_district_id']

In [5]:
# Create a new DataFrame to save the useful information
time_slot = pd.DataFrame({'stat' : orders.groupby(["time_slot"]).size()})
szone = pd.DataFrame({'stat' : orders.groupby(["start_district_id"]).size()})
ezone = pd.DataFrame({'stat' : orders.groupby(["dest_district_id"]).size()})
date = pd.DataFrame({'stat' : orders.groupby(["date"]).size()})
print (len(time_slot),len(szone), len(ezone), len(date))
in_d = pd.DataFrame(columns=['date', 'start_district_id', 'time_slot',"gap"])
n = 1
for d in date.index.values:    
    date = d
    print('date: '+ str(d))
    for z in szone.index.values:
        start = z
        for t in time_slot.index.values:
            time = t
            in_d.loc[n]=[date, start, time, 0.0]
            n+=1

27 66 66 5
date: 2016-01-23
date: 2016-01-25
date: 2016-01-27
date: 2016-01-29
date: 2016-01-31

In [6]:
# Create a new column called key which combines day, start district id and time slot. 
in_d['key'] = in_d["date"]
in_d['key'] = in_d.date.astype(str).str.cat(in_d.start_district_id.astype(str), sep='_').str.cat(in_d.time_slot.astype(int).astype(str), sep='_')
in_d["district_id"] = in_d["start_district_id"]

In [7]:
# Generate demand, supply and future supply (which depends on the destination of each order). Our naive model 
# will be based on these variables. Future supply will be an interesting attribute to dig in,

demand = pd.DataFrame({'demand' : orders.groupby( ['date', 'start_district_id', 'time_slot'] ).size()}).reset_index()
supply = pd.DataFrame({'demand' : orders.groupby( ['date', 'driver_id', 'time_slot'] ).size()}).reset_index()
fsupply = pd.DataFrame({'future_supply' : orders.groupby( ['date', 'dest_district_id', 'time_slot'] ).size()}).reset_index()
demand["district_id"] = demand['start_district_id']
fsupply["district_id"] = fsupply['dest_district_id']

In [8]:
# fill in the table with the information generated.

def join_value(left, right, key):
    left['key'] = left.date.astype(str).str.cat(left.district_id.astype(int).astype(str), sep='_').str.cat(left.time_slot.astype(int).astype(str), sep='_')
    right['key'] = right.date.astype(str).str.cat(right.district_id.astype(int).astype(str), sep='_').str.cat(right.time_slot.astype(int).astype(str), sep='_')
    left_a = left.set_index(key)
    right_a = right.set_index(key)

    res = left_a.loc[:, left_a.columns.union(right_a.columns)]
    res.update(right_a)
    return res

res = join_value(in_d, gap, "key")
res = join_value(res, demand, "key")
res = join_value(res, fsupply, "key")
res["time"] = res["time_slot"]/144*24
res.drop(["dest_district_id", "start_district_id"], axis=1,inplace=True) 
res["supply"] = res["demand"]-res["gap"]

print (res.sort_values(["gap"], ascending=False))

                         date  demand district_id  future_supply     gap  \
key
2016-01-29_51_92   2016-01-29  1735.0          51         1233.0  1185.0
2016-01-25_51_102  2016-01-25  1876.0          51         1202.0  1173.0
2016-01-29_51_127  2016-01-29  1672.0          51          792.0  1037.0
2016-01-23_51_127  2016-01-23  1462.0          51          646.0  1011.0
2016-01-23_51_126  2016-01-23  1466.0          51          671.0   959.0
2016-01-25_51_127  2016-01-25  1385.0          51          616.0   918.0
2016-01-29_51_91   2016-01-29  1358.0          51         1119.0   906.0
2016-01-29_51_90   2016-01-29  1321.0          51         1114.0   902.0
2016-01-25_51_104  2016-01-25  1443.0          51         1005.0   885.0
2016-01-27_51_103  2016-01-27  1493.0          51         1085.0   884.0
2016-01-29_51_102  2016-01-29  1577.0          51         1140.0   841.0
2016-01-27_51_104  2016-01-27  1403.0          51         1054.0   825.0
2016-01-29_51_128  2016-01-29  1439.0          51          761.0   811.0
2016-01-29_51_126  2016-01-29  1487.0          51          714.0   791.0
2016-01-29_51_104  2016-01-29  1424.0          51         1162.0   778.0
2016-01-27_51_102  2016-01-27  1436.0          51         1084.0   777.0
2016-01-29_51_103  2016-01-29  1445.0          51         1098.0   765.0
2016-01-25_51_126  2016-01-25  1304.0          51          558.0   754.0
2016-01-31_51_126  2016-01-31  1151.0          51          590.0   747.0
2016-01-27_51_127  2016-01-27  1215.0          51          570.0   726.0
2016-01-29_8_54    2016-01-29  1114.0           8          771.0   663.0
2016-01-31_51_104  2016-01-31  1254.0          51          995.0   662.0
2016-01-27_51_126  2016-01-27  1245.0          51          550.0   661.0
2016-01-29_37_55   2016-01-29   921.0          37          490.0   658.0
2016-01-23_51_128  2016-01-23  1111.0          51          521.0   655.0
2016-01-25_51_103  2016-01-25  1158.0          51          892.0   642.0
2016-01-29_37_54   2016-01-29   819.0          37          563.0   625.0
2016-01-31_51_102  2016-01-31  1142.0          51          931.0   622.0
2016-01-29_8_55    2016-01-29  1032.0           8          783.0   620.0
2016-01-25_48_102  2016-01-25  1034.0          48          548.0   609.0
...                       ...     ...         ...            ...     ...
2016-01-25_5_44    2016-01-25     NaN           5            NaN     0.0
2016-01-29_44_91   2016-01-29     NaN          44            NaN     0.0
2016-01-29_43_80   2016-01-29     2.0          43            4.0     0.0
2016-01-25_5_43    2016-01-25     NaN           5            NaN     0.0
2016-01-23_65_92   2016-01-23     1.0          65            NaN     0.0
2016-01-29_43_91   2016-01-29     3.0          43            4.0     0.0
2016-01-29_43_92   2016-01-29     NaN          43            7.0     0.0
2016-01-29_43_102  2016-01-29     5.0          43            6.0     0.0
2016-01-23_65_91   2016-01-23     4.0          65            NaN     0.0
2016-01-29_43_104  2016-01-29     1.0          43            3.0     0.0
2016-01-23_65_90   2016-01-23     1.0          65            NaN     0.0
2016-01-25_49_127  2016-01-25     2.0          49           11.0     0.0
2016-01-29_43_116  2016-01-29     1.0          43            2.0     0.0
2016-01-23_65_80   2016-01-23     5.0          65            1.0     0.0
2016-01-25_49_128  2016-01-25     2.0          49            8.0     0.0
2016-01-23_65_78   2016-01-23     3.0          65            NaN     0.0
2016-01-29_43_138  2016-01-29     1.0          43            1.0     0.0
2016-01-29_43_139  2016-01-29     NaN          43            1.0     0.0
2016-01-29_43_140  2016-01-29     NaN          43            1.0     0.0
2016-01-29_44_42   2016-01-29     NaN          44            NaN     0.0
2016-01-29_44_43   2016-01-29     NaN          44            NaN     0.0
2016-01-29_44_44   2016-01-29     NaN          44            NaN     0.0
2016-01-23_65_68   2016-01-23     1.0          65            1.0     0.0
2016-01-29_44_55   2016-01-29     1.0          44            3.0     0.0
2016-01-29_44_56   2016-01-29     NaN          44            NaN     0.0
2016-01-29_44_66   2016-01-29     2.0          44            NaN     0.0
2016-01-23_65_67   2016-01-23     1.0          65            NaN     0.0
2016-01-23_65_66   2016-01-23     2.0          65            NaN     0.0
2016-01-25_5_42    2016-01-25     NaN           5            NaN     0.0
2016-01-31_9_140   2016-01-31    11.0           9            6.0     0.0

                   time_slot       time  supply
key
2016-01-29_51_92        92.0  15.333333   550.0
2016-01-25_51_102      102.0  17.000000   703.0
2016-01-29_51_127      127.0  21.166667   635.0
2016-01-23_51_127      127.0  21.166667   451.0
2016-01-23_51_126      126.0  21.000000   507.0
2016-01-25_51_127      127.0  21.166667   467.0
2016-01-29_51_91        91.0  15.166667   452.0
2016-01-29_51_90        90.0  15.000000   419.0
2016-01-25_51_104      104.0  17.333333   558.0
2016-01-27_51_103      103.0  17.166667   609.0
2016-01-29_51_102      102.0  17.000000   736.0
2016-01-27_51_104      104.0  17.333333   578.0
2016-01-29_51_128      128.0  21.333333   628.0
2016-01-29_51_126      126.0  21.000000   696.0
2016-01-29_51_104      104.0  17.333333   646.0
2016-01-27_51_102      102.0  17.000000   659.0
2016-01-29_51_103      103.0  17.166667   680.0
2016-01-25_51_126      126.0  21.000000   550.0
2016-01-31_51_126      126.0  21.000000   404.0
2016-01-27_51_127      127.0  21.166667   489.0
2016-01-29_8_54         54.0   9.000000   451.0
2016-01-31_51_104      104.0  17.333333   592.0
2016-01-27_51_126      126.0  21.000000   584.0
2016-01-29_37_55        55.0   9.166667   263.0
2016-01-23_51_128      128.0  21.333333   456.0
2016-01-25_51_103      103.0  17.166667   516.0
2016-01-29_37_54        54.0   9.000000   194.0
2016-01-31_51_102      102.0  17.000000   520.0
2016-01-29_8_55         55.0   9.166667   412.0
2016-01-25_48_102      102.0  17.000000   425.0
...                      ...        ...     ...
2016-01-25_5_44         44.0   7.333333     NaN
2016-01-29_44_91        91.0  15.166667     NaN
2016-01-29_43_80        80.0  13.333333     2.0
2016-01-25_5_43         43.0   7.166667     NaN
2016-01-23_65_92        92.0  15.333333     1.0
2016-01-29_43_91        91.0  15.166667     3.0
2016-01-29_43_92        92.0  15.333333     NaN
2016-01-29_43_102      102.0  17.000000     5.0
2016-01-23_65_91        91.0  15.166667     4.0
2016-01-29_43_104      104.0  17.333333     1.0
2016-01-23_65_90        90.0  15.000000     1.0
2016-01-25_49_127      127.0  21.166667     2.0
2016-01-29_43_116      116.0  19.333333     1.0
2016-01-23_65_80        80.0  13.333333     5.0
2016-01-25_49_128      128.0  21.333333     2.0
2016-01-23_65_78        78.0  13.000000     3.0
2016-01-29_43_138      138.0  23.000000     1.0
2016-01-29_43_139      139.0  23.166667     NaN
2016-01-29_43_140      140.0  23.333333     NaN
2016-01-29_44_42        42.0   7.000000     NaN
2016-01-29_44_43        43.0   7.166667     NaN
2016-01-29_44_44        44.0   7.333333     NaN
2016-01-23_65_68        68.0  11.333333     1.0
2016-01-29_44_55        55.0   9.166667     1.0
2016-01-29_44_56        56.0   9.333333     NaN
2016-01-29_44_66        66.0  11.000000     2.0
2016-01-23_65_67        67.0  11.166667     1.0
2016-01-23_65_66        66.0  11.000000     2.0
2016-01-25_5_42         42.0   7.000000     NaN
2016-01-31_9_140       140.0  23.333333    11.0

[8910 rows x 8 columns]

In [9]:
res['district_id'] = res['district_id'].astype(int)
res = res.sort_values(["district_id", "date", "time_slot"], ascending=True)
res = res.reset_index()
res.drop('key', 1)

,date,demand,district_id,future_supply,gap,time_slot,time,supply
0,2016-01-23,64.0,1,64.0,9.0,42.0,7.000000,55.0
1,2016-01-23,76.0,1,81.0,11.0,43.0,7.166667,65.0
2,2016-01-23,96.0,1,99.0,6.0,44.0,7.333333,90.0
3,2016-01-23,227.0,1,225.0,8.0,54.0,9.000000,219.0
4,2016-01-23,205.0,1,214.0,6.0,55.0,9.166667,199.0
5,2016-01-23,146.0,1,144.0,7.0,56.0,9.333333,139.0
6,2016-01-23,121.0,1,126.0,3.0,66.0,11.000000,118.0
7,2016-01-23,151.0,1,135.0,4.0,67.0,11.166667,147.0
8,2016-01-23,155.0,1,126.0,4.0,68.0,11.333333,151.0
9,2016-01-23,194.0,1,165.0,7.0,78.0,13.000000,187.0
10,2016-01-23,191.0,1,165.0,6.0,79.0,13.166667,185.0
11,2016-01-23,193.0,1,171.0,8.0,80.0,13.333333,185.0
12,2016-01-23,161.0,1,161.0,3.0,90.0,15.000000,158.0
13,2016-01-23,160.0,1,146.0,4.0,91.0,15.166667,156.0
14,2016-01-23,180.0,1,170.0,4.0,92.0,15.333333,176.0
15,2016-01-23,292.0,1,254.0,16.0,102.0,17.000000,276.0
16,2016-01-23,292.0,1,284.0,7.0,103.0,17.166667,285.0
17,2016-01-23,257.0,1,245.0,4.0,104.0,17.333333,253.0
18,2016-01-23,270.0,1,202.0,10.0,114.0,19.000000,260.0
19,2016-01-23,217.0,1,166.0,5.0,115.0,19.166667,212.0
20,2016-01-23,261.0,1,186.0,4.0,116.0,19.333333,257.0
21,2016-01-23,343.0,1,235.0,8.0,126.0,21.000000,335.0
22,2016-01-23,312.0,1,196.0,10.0,127.0,21.166667,302.0
23,2016-01-23,261.0,1,170.0,4.0,128.0,21.333333,257.0
24,2016-01-23,134.0,1,79.0,4.0,138.0,23.000000,130.0
25,2016-01-23,93.0,1,57.0,5.0,139.0,23.166667,88.0
26,2016-01-23,104.0,1,85.0,6.0,140.0,23.333333,98.0
27,2016-01-25,NaN,1,NaN,0.0,42.0,7.000000,NaN
28,2016-01-25,NaN,1,NaN,0.0,43.0,7.166667,NaN
29,2016-01-25,NaN,1,NaN,0.0,44.0,7.333333,NaN
...,...,...,...,...,...,...,...,...
8880,2016-01-29,11.0,66,2.0,0.0,138.0,23.000000,11.0
8881,2016-01-29,6.0,66,NaN,0.0,139.0,23.166667,6.0
8882,2016-01-29,10.0,66,5.0,0.0,140.0,23.333333,10.0
8883,2016-01-31,6.0,66,NaN,0.0,42.0,7.000000,6.0
8884,2016-01-31,10.0,66,7.0,0.0,43.0,7.166667,10.0
8885,2016-01-31,4.0,66,NaN,0.0,44.0,7.333333,4.0
8886,2016-01-31,8.0,66,4.0,0.0,54.0,9.000000,8.0
8887,2016-01-31,18.0,66,8.0,0.0,55.0,9.166667,18.0
8888,2016-01-31,15.0,66,6.0,0.0,56.0,9.333333,15.0
8889,2016-01-31,19.0,66,9.0,0.0,66.0,11.000000,19.0
8890,2016-01-31,16.0,66,5.0,0.0,67.0,11.166667,16.0
8891,2016-01-31,15.0,66,9.0,0.0,68.0,11.333333,15.0
8892,2016-01-31,19.0,66,7.0,0.0,78.0,13.000000,19.0
8893,2016-01-31,14.0,66,7.0,0.0,79.0,13.166667,14.0
8894,2016-01-31,16.0,66,5.0,0.0,80.0,13.333333,16.0
8895,2016-01-31,21.0,66,8.0,2.0,90.0,15.000000,19.0
8896,2016-01-31,27.0,66,8.0,1.0,91.0,15.166667,26.0
8897,2016-01-31,26.0,66,9.0,1.0,92.0,15.333333,25.0
8898,2016-01-31,42.0,66,15.0,0.0,102.0,17.000000,42.0
8899,2016-01-31,41.0,66,12.0,1.0,103.0,17.166667,40.0
8900,2016-01-31,31.0,66,8.0,0.0,104.0,17.333333,31.0
8901,2016-01-31,20.0,66,6.0,0.0,114.0,19.000000,20.0
8902,2016-01-31,22.0,66,7.0,0.0,115.0,19.166667,22.0
8903,2016-01-31,24.0,66,6.0,0.0,116.0,19.333333,24.0
8904,2016-01-31,17.0,66,9.0,0.0,126.0,21.000000,17.0
8905,2016-01-31,13.0,66,7.0,0.0,127.0,21.166667,13.0
8906,2016-01-31,18.0,66,7.0,0.0,128.0,21.333333,18.0
8907,2016-01-31,10.0,66,4.0,0.0,138.0,23.000000,10.0
8908,2016-01-31,4.0,66,2.0,0.0,139.0,23.166667,4.0
8909,2016-01-31,9.0,66,3.0,0.0,140.0,23.333333,9.0

In [10]:
train_x = res['gap'].as_matrix().astype(float)

In [12]:
import numpy as np
train_x1 = np.zeros(8910//3)
train_x2 = np.zeros(8910//3)
train_x3 = np.zeros(8910//3)

In [13]:
train = train_x1
for i in range(8910):
    if i%3 == 0:
        train_x1[i//3] = train_x[i]
    if i%3 == 1:
        train_x2[i//3] = train_x[i]
    if i%3 == 2:
        train_x3[i//3] = train_x[i]
train = (train_x1*0.65+train_x2*0.25+train_x3*0.15)/2
train = np.maximum(np.ones(8910//3),train)

In [16]:
train

array([ 4.75 ,  3.875,  1.775, ...,  1.   ,  1.   ,  1.   ])

In [17]:
re = res
re['0'] = 1
a = range(0,len(re))
re['0'] = a
re['0'] = re['0']%3
re = re.drop(re[re['0']!=0].index)

In [18]:
re['0'] = train

In [19]:
re = re.reset_index()
re['time_slot'] = re['time_slot'] + 4
re['key'] = re.date.astype(str).str.cat(re.time_slot.astype(int).astype(str), sep='-')
re = re.sort_values(['date','time_slot', "district_id"], ascending=True)

In [35]:
submission = pd.DataFrame()
submission['0'] = re['district_id']
submission['1'] = re['key']
submission['2'] = re['0']
submission.to_csv('submission1.csv', index = False, header = False)

In [33]:
submission

       0               1       2
0      1   2016-01-23-46   4.750
45     2   2016-01-23-46   1.000
90     3   2016-01-23-46   1.000
135    4   2016-01-23-46   6.500
180    5   2016-01-23-46   1.000
225    6   2016-01-23-46   2.425
270    7   2016-01-23-46   7.400
315    8   2016-01-23-46  24.975
360    9   2016-01-23-46   1.175
405   10   2016-01-23-46   1.000
450   11   2016-01-23-46   1.825
495   12   2016-01-23-46   8.900
540   13   2016-01-23-46   1.000
585   14   2016-01-23-46   6.050
630   15   2016-01-23-46   1.000
675   16   2016-01-23-46   1.000
720   17   2016-01-23-46   4.175
765   18   2016-01-23-46   1.000
810   19   2016-01-23-46   6.525
855   20   2016-01-23-46   4.000
900   21   2016-01-23-46   2.100
945   22   2016-01-23-46   1.550
990   23   2016-01-23-46  23.900
1035  24   2016-01-23-46  15.325
1080  25   2016-01-23-46   1.775
1125  26   2016-01-23-46   6.450
1170  27   2016-01-23-46   2.125
1215  28   2016-01-23-46   9.775
1260  29   2016-01-23-46   5.300
1305  30   2016-01-23-46   1.000
...   ..             ...     ...
1664  37  2016-01-31-142   1.375
1709  38  2016-01-31-142   1.000
1754  39  2016-01-31-142   1.000
1799  40  2016-01-31-142   1.000
1844  41  2016-01-31-142   1.000
1889  42  2016-01-31-142   2.100
1934  43  2016-01-31-142   1.000
1979  44  2016-01-31-142   1.000
2024  45  2016-01-31-142   1.000
2069  46  2016-01-31-142   1.000
2114  47  2016-01-31-142   1.000
2159  48  2016-01-31-142   2.250
2204  49  2016-01-31-142   2.275
2249  50  2016-01-31-142   1.000
2294  51  2016-01-31-142  14.600
2339  52  2016-01-31-142   1.000
2384  53  2016-01-31-142   1.000
2429  54  2016-01-31-142   1.000
2474  55  2016-01-31-142   1.000
2519  56  2016-01-31-142   1.000
2564  57  2016-01-31-142   1.000
2609  58  2016-01-31-142   1.000
2654  59  2016-01-31-142   1.000
2699  60  2016-01-31-142   1.000
2744  61  2016-01-31-142   1.000
2789  62  2016-01-31-142   1.000
2834  63  2016-01-31-142   1.000
2879  64  2016-01-31-142   1.000
2924  65  2016-01-31-142   1.000
2969  66  2016-01-31-142   1.000

[2970 rows x 3 columns]